# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 740b97c3ba1c05e75c1a85bae1dfbbca73d0d4212f3b644af5938abc209048b0b9e52113f7cd13e890ac040c44f6708618f4a1e04dfc75a530c2c779c949586b

test:
  secret_key_base: 581d712c760089e1afe1fb6afe59d9847c46b2caed346dd408a333f03adfe1fddcf18ab21d9fe8494ea40d2fe0d048f6ffe3d05a9f6e1c55368764fe38f7bfbd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
